# Generated by Django 5.2.5 on 2025-10-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='country',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='country',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
